### ISSUE TITLE
Customize theme

### ISSUE THREAD

**Issue by scottgerring** [HiDeoo/astro-d2#29]
### Is your feature request related to a problem?

I'd like to be able to customize the theme of _all_ diagrams generated, e.g., to globally change background colours.

As it stands it seems like I can only do this by using a diagram like this:

```d2
vars: {
 d2-config: {
  dark-theme-overrides: {
      /* Background */
      N7: "#1d1e21"
  }
  theme-overrides: {
     N7: "#fafafa"
  }
 }
}

direction: right
A -> B

```

... which works, but is very repetitive!

### Describe the solution you'd like

It'd be great to be able to provide `d2-config` blocks to the configuration setup in `d2({})`, or alternatively, to provide some mechanism to transform _all_ diagram source files as they are passed through - for instance, to prepend inline theme info.

**Comment by Samreay** [comment]
I'd be interested in this feature too, so I can match background colours and website themes given d2 comes with only one dark theme out of the box. @scottgerring is the example code you have above correct - there are some mismatched braces there and I've yet to find a way that even inline changes the theme.

**Comment by scottgerring** [comment]
You're right, I did a rubbish job copying it. corrected inline 💪 

I've gone down this path a bit, and it works, but yeah, lots of copy paste isn't very satisfying. And, I will have to do replace-in-files when I want to change colours again. Would be great to do it in the theme config!

**Comment by HiDeoo** [comment]
Thanks for the feedback everyone :raised_hands: 

One of the characteristics of the plugin is that it actually never read or change/modify the diagram definition. Providing a mechanism to add some content or transform diagrams from the plugin would most likely require a parser and a serializer for the diagram definition to do that in a safe way. I'm not even sure if this is something that already exists in the Node.js ecosystem or not, but this would also bring a lot of complexity to the plugin.

I didn't give a lot of thought to this feature as I don't heavily use themes in my diagrams, but I think that the same issue is not limited to this plugin but would also apply to someone authoring D2 diagrams through the CLI and wanting a custom theme in all diagrams. Personally, I think this may be a good feature to have in D2 to allow users to add custom themes instead of having to modify them.

That being said, it's currently possible to workaround the issue partially by relying on D2 [imports](https://d2lang.com/tour/imports) syntax.

For example, you could create an `src/assets/theme.d2` file with the following content:

```d2
vars: {
  d2-config: {
    theme-overrides: {
      B1: "#F44336"
    }
    dark-theme-overrides: {
      B1: "#00FF00"
    }
  }
}
```

And in a `src/content/docs/test.md` file where you are defining a diagram, you could import the theme file using a relative path like this:

````md
---
title: Custom theme test
---

Hello

```d2
...@../../assets/theme.d2

direction: right
A -> B
```
````

This would render as expected with custom connections and border colors:

<img width="444" alt="SCR-20241125-juzc" src="https://github.com/user-attachments/assets/c1193f33-8e96-4614-b791-d6a8b901606d">
<img width="444" alt="SCR-20241125-juzu" src="https://github.com/user-attachments/assets/ab12fc78-e76f-4a83-89e9-9bf5f5365d68">


If the ability to add custom themes to D2 is something that ends up being implemented, or made easier in some way, I'll be more than happy to update the plugin to support it.

**Comment by scottgerring** [comment]
Hey @HiDeoo,

> That being said, it's currently possible to workaround the issue partially by relying on D2 [imports](https://d2lang.com/tour/imports) syntax.

I had no idea - this is a practical workaround. Thanks!
